# Generated by Django 4.1 on 2023-04-06 13:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regionId", models.PositiveIntegerField()),
                ("region", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gln", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user", models.Model),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Drugs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gtin", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=256)),
                ("domain", models.PositiveIntegerField(null=True)),
                ("legal", models.BooleanField(null=True)),
                ("marketing", models.BooleanField(null=True)),
                ("drugStatus", models.BooleanField(null=True)),
                ("importable", models.BooleanField(null=True)),
                ("exportable", models.BooleanField(null=True)),
                ("registrationNumber", models.CharField(max_length=256)),
                ("genericName", models.CharField(max_length=256, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, max_digits=256, null=True),
                ),
                ("dosage", models.CharField(max_length=256, null=True)),
                ("packageSize", models.CharField(max_length=256, null=True)),
                ("packageType", models.CharField(max_length=256, null=True)),
                ("strength", models.CharField(max_length=256, null=True)),
                ("unitStrength", models.CharField(max_length=256, null=True)),
                ("volume", models.CharField(max_length=256, null=True)),
                ("volumeUnit", models.CharField(max_length=256, null=True)),
                ("suppliers", models.ManyToManyField(null=True, to="rsd_app.supplier")),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cityId", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=256)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resides",
                        to="rsd_app.region",
                    ),
                ),
            ],
        ),
    ]
