# Generated by Django 4.1 on 2023-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rsd_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugs",
            name="registrationNumber",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
