# Generated by Django 4.1 on 2023-03-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_region_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resides",
                to="account.region",
            ),
        ),
    ]
